### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by nickstanish** [nickstanish/visual-audio-js#16]
- [x] soundcloud url source
- [ ] mp3 url source
- [ ] youtube video source
- [ ] drop files into window
- [ ] tempo detection
- [ ] different visualization patterns
